//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thestudent
    {
        public int id { get; set; }
        public int Student_number { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Campus { get; set; }
        public string Department { get; set; }
        public Nullable<int> Desired_bus { get; set; }
        public Nullable<int> Desired_time { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual time time { get; set; }
    }
}
